apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replicas:
  - name: api
    count: 1

images:
  - name: cka-api
    newName: ghcr.io/yifunlin/cka-api
    newTag: 8f7c13e32e9b6e62e3e85e12242a2a546641413f
