apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replicas:
  - name: api
    count: 1

images:
  - name: cka-api
    newName: ghcr.io/yifunlin/cka-api
    newTag: 55a01a226613b218ce10afbdf567ebaabfae912c
